site_name: SPK DevBlog
site_description: Site for blogging development moments
copyright: Copyright &copy; 2023 Yegor Latushko

repo_url: https://github.com/latushko1/spkschedule-blog

extra_css:
  - stylesheets/extra.css

nav:
  - Главная: index.md
  - Блог:
      - blog/index.md
      - Обновления:
          - blog/updates/add-teachers.md
#          - blog/updates/second.md
#      - Subtopic:
#          - blog/subtopic/interesting-post.md
theme:
  custom_dir: overrides
  name: material
  font:
    text: Noto Sans
  icon:
    logo: material/home
  # Light and Dark Theme Toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: degault
      primary: cyan
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - toc.integrate
    - header.autohide

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/latushko1
  blog:
    dir: blog
    author: Yegor Latushko
    author_image: https://sun9-49.userapi.com/impg/7w6YxKLlBxprnANhN6ZgqS4nCTUXeiTuauwMKA/nLFs7i4x50M.jpg?size=1200x1600&quality=95&sign=aceedf1e36947208b0e65a4528f19c24&type=album
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true

markdown_extensions:
  - toc:
      title: На этой странице
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

