site_name: SPK DevBlog
site_description: Site for blogging development moments
copyright: Copyright &copy; 2023 Yegor Latushko

repo_url: https://github.com/latushko1/spkschedule-blog

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
#      - 2021:
#          - blog/2021/core-web-vitals.md
#          - blog/2021/cooking-post.md
#      - Subtopic:
#          - blog/subtopic/interesting-post.md
theme:
  custom_dir: overrides
  name: material
  font: false
  icon:
    logo: material/home
  # Light and Dark Theme Toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/latushko1
  blog:
    dir: blog
    author: Yegor Latushko
    author_image: https://sun9-49.userapi.com/impg/7w6YxKLlBxprnANhN6ZgqS4nCTUXeiTuauwMKA/nLFs7i4x50M.jpg?size=1200x1600&quality=95&sign=aceedf1e36947208b0e65a4528f19c24&type=album
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true

markdown_extensions:
  - toc:
      title: На этой странице
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

